[package]
name = "octree_voxel_stair_detection_ros"
version = "0.1.0"
authors = ["yukimakura <yukimakura86@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosrust = "0.9"